### ISSUE TITLE
Bird E-Scooters change bike_id

### ISSUE THREAD

**Issue by PaulKC** [SFOE/sharedmobility#1]
It looks like the bike_ids of the Bird E-Scooters are changing over time. Is this expected behaviour?

**Comment by SFOE** [comment]
Bike_id rotation was added in GBFS Version 2.0. (see [pr147](https://github.com/NABSA/gbfs/pull/147) and is therefore expected. However this is not fully supported by all providers (see [our differences from GBFS](https://github.com/SFOE/sharedmobility/blob/main/Additions%20to%20GBFS.md#differences).

**Comment by PaulKC** [comment]
Thank you for the clarification.
