### ISSUE TITLE
Stations of provider "emobility" not updated

### ISSUE THREAD

**Issue by nrohrbach** [SFOE/sharedmobility#13]
The stations of provider "emobility" are not updated at the moment.
We will fix this issue as soon as possible.

Best regards
Nico

**Comment by nrohrbach** [comment]
The stations of provider "emobility" are updating again.

Best regards
Nico

**Comment by bsl546** [comment]
Hello everyone.
There are still issues on the datasets.  In particular, it seems now that some data are wrong concerning the emobility. In Bern station, e.g. emobility and mobility vehicles seem to be exactly the same. There should actually only be two electric cars in Bern. Do you know how to solve that issue?

**Comment by nrohrbach** [comment]
Hi there
Thanks for your hint. I forwarded this issue to the service provider and will let you know as soon as it is fixed.

**Comment by nrohrbach** [comment]
Hi @bsl546 
The issue with the providers emobility and mobility was fixed.

Best regards
Nico
