### ISSUE TITLE
Entire service down

### ISSUE THREAD

**Issue by bsl546** [SFOE/sharedmobility#14]
Dear all, 

The entire service seems to be down since 29.01.2022, 16:00. I thank you in advance for your help,

**Comment by nrohrbach** [comment]
Yes. Unfortunately we have a problem with our system. I hope to fix the error as soon as possible.

Best regards
Nico

**Comment by PierrickP** [comment]
Hello, is it down again ?
How can we help you ?

**Comment by nrohrbach** [comment]
Hi Pierrick

Unfortunately we have again problems with our system since Friday evening. I hope to fix it soon and make it more stable afterwards.

**Comment by nrohrbach** [comment]
The service is running again.
Sorry for the inconvenience.
