### ISSUE TITLE
Send permissive CORS headers form GBFS endpoints

### ISSUE THREAD

**Issue by efrainsteinbach** [SFOE/sharedmobility#15]
Currently, the response headers from the GBFS endpoints on _sharedmobility.ch_ do not send any CORS headers. This means that a properly behaving browser will block sending an XHttpRequest (AJAX request) from a web application to the API (unless such a web app was hosted on the domain _sharedmobility.ch_). So only native clients which ignore such security concerns will be able to use the API,  browser-run JavaScript apps won't.

I can work around this by using a proxy API, which relays the requests and adds these CORS headers when returning the response. However, it would be cool if you could add this to your web server configuration (nginx), so I don't need this extra proxy in between.

**Comment by nrohrbach** [comment]
Dear @efrainsteinbach 
I have forwarded your request to the system provider and will let you know as soon as we have added CORS headers

Best regards
Nico

**Comment by nrohrbach** [comment]
The GBFS endpoint should now work with CORS headers. Please inform us if it is not working properly.

Best regards
Nico

**Comment by efrainsteinbach** [comment]
Great, it works! Thanks!
