### ISSUE TITLE
Are the positions being updated?

### ISSUE THREAD

**Issue by WillTheGeek** [SFOE/sharedmobility#16]
I checked the live map just now (Tuesday, June 6th 2023 14.08 CEST), and all the availability timestamps I've checked are from May 30th 2023. Any ideas whats going on?

**Comment by nrohrbach** [comment]
Yes you are rigth. Something is wrong. We will fix the problem as soon as possible.

**Comment by nrohrbach** [comment]
The map and the data is updated again.

Best regards
Nico

**Comment by WillTheGeek** [comment]
Thanks, Nico!

**Comment by WillTheGeek** [comment]
Hi Nico,
Just wanted to follow up with an observation about the provider Lime Zurich Ebike. It seems that those e-bikes are not changing their position (measured by the lon/lat variables) over time. Have you had a similar experience?

Best,
Will
