### ISSUE TITLE
[Rent a Bike] Number of bikes per stations seem incorrect

### ISSUE THREAD

**Issue by PierrickP** [SFOE/sharedmobility#4]
Hello,

After comparing 2 stations from the official website https://www.rentabike.ch/ and the data feed (visible on https://map.geo.admin.ch/), the count of vehicles per stations seen not be exact.

At the station "Airolo - Hotel Forni"

![image](https://user-images.githubusercontent.com/1214544/118501910-7d614180-b729-11eb-861a-5a671fbb1798.png)

![image](https://user-images.githubusercontent.com/1214544/118502020-94a02f00-b729-11eb-91bf-bbe24b0d950d.png)

Another strange things, the number of ebike are always egals to the number of mecanical bike.
How could we be sure of the data quality ?

And for the end, `num_docks_available` is always 999. If the real number is not available, i would prefer `null`

Thanks

**Comment by nrohrbach** [comment]
This provider was deactivated due to a deactivated API.
