### ISSUE TITLE
[Mobility] all stations are "unavailable"

### ISSUE THREAD

**Issue by PierrickP** [SFOE/sharedmobility#5]
All Mobility stations have

```
    "is_installed": **false**,
    "is_renting": **false**,
    "is_returning": **false**,
```

theoretically they should be treat as unavailable stations.
But i am convinced that this is a mistake ;)

**Comment by SFOE** [comment]
Hi PierrickP
Yes this is wrong. Will be fixed for the following providers: mobility, emobility and sponticar.

**Comment by PierrickP** [comment]
@SFOE awesome !

**Comment by SFOE** [comment]
This issue is fixed.
